service: olio-graphql-lambda
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  lambdaHashingVersion: 20201221

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  graphql:
    handler: app.graphqlHandler
    environment:
      STAGE: ${sls:stage}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

package:
  patterns:
    - "!node_modules/**/query-engine-**"
    - "!node_modules/@prisma/engines/**"
    - "!prisma/migrations/**"
    - node_modules/.prisma/client/query-engine-rhel-*

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  dotenv:
    required:
      env:
        - JWT_SECRET_KEY
        - SALT
        - NODEMAILER_USER
        - NODEMAILER_PASS
        - AWS_BUCKET_NAME
        - DATABASE_URL
