service: olio-graphql-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
functions:
  graphql:
    handler: app.graphqlHandler
    environment:
      STAGE: ${sls:stage}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

package:
  patterns:
    - "!node_modules/**/query-engine-**"
    - "!node_modules/@prisma/engines/**"
    - node_modules/.prisma/client/query-engine-rhel-*
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    required:
      env:
        - JWT_SECRET_KEY
        - SALT
        - NODEMAILER_USER
        - NODEMAILER_PASS
        - AWS_BUCKET_NAME
        - DATABASE_URL
