name: Deploy To Lambda for dev

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF

      - name: Install yarn packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Setup Prisma
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: migrate:dev

      - name: Deploy using Serverless
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
